apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: istio
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - description: Exemptions necessary for Istio CNI to manage network configurations and ensure proper traffic routing
      matcher:
        kind: pod
        name: istio-cni-node.*
        namespace: istio-system
      policies:
        - RequireNonRootUser
        - RestrictVolumeTypes
        - DisallowHostNamespaces
        - RestrictCapabilities
        - RestrictHostPathWrite
        - RestrictHostPorts
        - RestrictSELinuxType
      title: Istio CNI exemptions
    - description: Exemptions necessary for ztunnel to manage network traffic and ensure secure data plane operations
      matcher:
        kind: pod
        name: ztunnel.*
        namespace: istio-system
      policies:
        - RestrictIstioUser
        - DisallowPrivileged
        - RequireNonRootUser
        - RestrictVolumeTypes
        - RestrictCapabilities
        - RestrictHostPathWrite
        - RestrictSELinuxType
      title: Istio ztunnel exemptions
